version: '2.4'

volumes:
  db_data:
    driver: local
  public:
    driver: local

services: 
  release:
    image: 410898520882.dkr.ecr.ap-northeast-1.amazonaws.com/micropost:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      host: db
      username: root
      password: Adsf4231!
  app:
    image: 410898520882.dkr.ecr.ap-northeast-1.amazonaws.com/micropost:tag${APP_VERSION}
    extends:
      service: release
  migrate:
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c '
      rails db:create && 
      rails db:migrate 
      '
  db:
    image: mysql:8.2 
    container_name: db
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Adsf4231!
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 10    
    
