version: '2.4'

volumes:
  db_data:
    driver: local
  public:
    driver: local

services: 
  release:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      username: root
      password: Adsf4231!
      host: db
  db:
    image: mysql:8.2 
    container_name: db
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Adsf4231!
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 10    
  app:
    extends:
      service: release
    healthcheck:
      test: curl -fs localhost:3000
      interval: 3s
      retries: 10
    volumes: 
      - .:/micropost
    ports: 
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    links:
      - db
    command: rails s -p 3000 -b 0.0.0.0
    #command: bash -c bundle exec unicorn_rails -c /app/config/unicorn.rb -D
  migrate:
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c '
      rails db:create && 
      rails db:migrate 
      '
    
