AWSTemplateFormatVersion: 2010-09-09
Description: AWS-ECS-Micropost-ECR
Resources: 
  Micropost:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: micropost
      EmptyOnDelete: true
      LifecyclePolicy: 
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Untagged images",
                "selection": {
                    "tagStatus": "untagged",
                    "countType": "sinceImagePushed",
                    "countUnit": "days",
                    "countNumber": 5
                },
                "action": {"type": "expire"}
              }
            ]
          }