AWSTemplateFormatVersion: 2010-09-09

Description: TackDefinition for AWS-ECS-Micropost

Parameters:
# デプロイするコンテナイメージのタグを指定する。デフォルトはlatest.
  ApplicationImageTag:
    Type: String
    Description: Application Docker Image Tag
    Default: latest  
    
  DatabasePassword:
    Type: String
    Description: Database password
    NoEcho: "true"

    
Resources: 
  MicropostTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: micropost
      Volumes:
        - Name: public
          Host:
            SourcePath: /data/public
      ContainerDefinitions:
        - Name: micropost
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/micropost:${ApplicationImageTag}
          MemoryReservation: 395
          Cpu: 245
          MountPoints:
            - SourceVolume: public
              ContainerPath: /public
          Environment:
            - Name: MYSQL_HOST
              Value: !ImportValue RdsEndpoint
            - Name: MYSQL_USER
              Value: admin
            - Name: MYSQL_PASSWORD
              Value: !Ref DatabasePassword
          Command: 
            - rails 
            - server
            - -p
            - 3000
            - -b
            - 0.0.0.0
          PortMappings:
            - ContainerPort: 3000
              HostPort: 0
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /${AWS::StackName}/ecs/micropost
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: docker
#CloudWatch Logsロググループ作成
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /${AWS::StackName}/ecs/micropost
      RetentionInDays: 3

Outputs:
  EcsTask: 
    Description: The TASK Definition to use for resouces
    Value: !Ref MicropostTaskDefinition
    Export:
      Name: EcsTask
